### ISSUE TITLE
DSC unable to retrieve portal token after 1.1.0

### ISSUE THREAD

**Issue by RQF4** [Esri/arcgis-powershell-dsc#101]
Hi Everyone,

First, thanks for all the contributions and work on this project! I've run into an issue with a previously running build after going to 1.1.0, although I've changed the config since then too. When running the attached base deployment federation fails with the following error:

>PowerShell DSC resource ArcGIS_Federation  failed to execute Test-TargetResource functionality with error message: Unable to retrieve Portal Token for 'AdminAccount' from Deployment 'https://<span></span>306.[redacted].com'

I have verified that the account used is being created as an admin in the portal. I can also log into /home , /portaladmin, and /sharing using the credentials as well as /generateToken with it.  

[base.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2444893/base.txt)
[307_mof.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2444894/307_mof.txt)
[ArcGISFederation-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2444909/ArcGISFederation-Error.txt)
[ArcGISFederation-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2444910/ArcGISFederation-Verbose.txt)

I can run in debug mode and step through ArcGIS.psm1 but I'm not sure how to debug whats running on the nodes?

~Thanks

**Comment by shailesh91** [comment]
Hey Corey,

Looks like there are errors in your config file for version 1.1 of this module.  
1. **"Target"** Parameter in SSL Certificate Block is now a required param
2. No node in Config file is assigned a Fileshare role. This is necessary since we create a file share for the deployment. As of now, we don't support external file shares.
2. **FileShareLocalPath**  should be a local file path, again looks like you are using an external file share. (It is in the roadmap but not fully tested). 
3. As of now, the is configured for both server and portal. You can't use them with only one as you are using as of now. **ContentDirectoryLocation** in the portal config block also needs to be a file share path using the same file share path as the one given for **ContentDirectoryLocation** of the server.
4. You don't need the federation block. It is required only for federated servers with specialized roles.

PS. I think a combination of the following two config files can help
* https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/Base%20Deployment/BaseDeployment-DualMachine.json
* https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/Base%20Deployment/BaseDeployment-ThreeMachine-10.6-ssl-per-Node-Example1.json

@RQF4 you can email me at shgoel@esri.com . We can discuss your specific use case on Skype.

Thanks,
Shailesh

**Comment by shailesh91** [comment]
Support for external file shares and the File Share only being used only for server or portal for "ContentDirectoryLocation" was added.
