### ISSUE TITLE
WaitForServerConfigToCompleteWA Unable to connect to the remote server

### ISSUE THREAD

**Issue by hmelendez** [Esri/arcgis-powershell-dsc#124]
I would like to understand what this validation is trying to do that it never gets to connect to the GIS Server. Is it an SSL handshake, WinRM or what?  After the Test fails 101 times the Set completed successfully.
[debug_log.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2829697/debug_log.txt)

**Comment by shailesh91** [comment]
"WaitForServerConfigToCompleteWATest-GIS01" is trying to check if the server (on another machine) has already been configured. If so only then proceed with the next step of configuring the web adaptor. There was an issue (#123) reported recently where the port on server machine was not opened when web adaptor and server are on different machine. That could be one of the reasons this check is failing.
Can you try manually opening port 6080, 6443 on the server machine and then retry running the config?

**Comment by hmelendez** [comment]
The site is to be https only and 6443 is the only server port open between web server and gis server. Does the tool require 6080 to be able to pass that test?

**Comment by shailesh91** [comment]
6443 is enough for this test.

**Comment by hmelendez** [comment]
Port 6443 is enabled, 6080 is not. Still, the test fails but the actual configuration succeeds is just that it takes close to two hours of fail attempts to move to the next step. I did notice that the TLS 1.1, 1.2 aren't enable on the web server. This are the default protocols that are enabled on the GIS Server. I'm wondering if it migh be an ssl handshake issue and how could I enable those protocols for the WINRM account,

**Comment by shailesh91** [comment]
We do a simple server token check to see if the site is configured or not. Since this specific request is going through the web server, we are using the FQDN of the Server machine and we enforce TLS1.1 and TLS 1.2 at the request time, I don't think that is the reason. 
```[System.Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls```
@hmelendez  Can you attach the JSON config?

**Comment by hmelendez** [comment]
Here is the config.json for the federated server.
[GenPurp.json.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2862381/GenPurp.json.txt)

**Comment by shailesh91** [comment]
@hmelendez Your config looks to be okay. But I still think the issue is related to the ports on Server Machine. There is one other thing you can do. You can modify this line to add ```-Verbose``` option and then run the config again. This might provide a little more verbosity.
https://github.com/Esri/arcgis-powershell-dsc/blob/0fa1ca8dcadaaa83b791bf48468787458a76dd3c/Modules/ArcGIS/DSCResources/ArcGIS_WaitForComponent/ArcGIS_WaitForComponent.psm1#L104

**Comment by shailesh91** [comment]
@hmelendez are you still getting this error?

**Comment by hmelendez** [comment]
> @hmelendez are you still getting this error?

Yes I continue to get the same issue. I added the -Verbose on line 104 as you requested but I did not see any diference in the log.
[Install_BaseDeployment_20190520_165113.log](https://github.com/Esri/arcgis-powershell-dsc/files/3196320/Install_BaseDeployment_20190520_165113.log)

**Comment by cameronkroeker** [comment]
Hello @hmelendez,

We have addressed this issue in the latest release, v3.0.0:

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.0.0

Thanks,
Cameron K.
