### ISSUE TITLE
Support for several licence files 

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#131]
Hello,

Following issue https://github.com/Esri/arcgis-powershell-dsc/issues/130, I realized that it is not possible to authorize an ArcGIS Server with several roles.
Indeed, if you generated a .prvc with 2 roles and 1 extension (eg: ArcGIS server standard + Image Server + Network analyst), only 1 role and the extension are activated by the licence manager (it is the same when it is done manually I believe).

I thought I would duplicate the file and switch the order of the 2 roles in the file but realized it is not possible to specify an array of LicenseFilePath.

What is the best strategy ?

Thanks

**Comment by nshampur** [comment]
It's usually not recommended to have the same server perform multiple roles. 
However the license manager should accept all information provided in the license file.

Are you observing consistent behavior where it does not apply?

**Comment by Biboba** [comment]
Thanks for the reply.
Yes, I am observing consistent behavior where it does not apply. Also with the Wizard.

My prvc is like ending like that:
// Features and authorization numbers
ArcGIS Server=ECPAAAAAAAAA
ArcGIS Server=ECPBBBBBBBBBB
Network Analyst Server=ECPCCCCCCCCC

The second role is not installed. If I switch the order, then it is the other one which is not authorized.
But the extension is always successfully authorized.

Thanks

**Comment by nshampur** [comment]
what version are you observing this behavior with?

**Comment by Biboba** [comment]
10.6.1

**Comment by nshampur** [comment]
let me check with out licensing team and see what behavior is expected.

**Comment by nshampur** [comment]
I spoke to our licensing experts and the workaround for this scenario (since our automation does not support a sequence of multiple licensing files) is to make the Feature name unique. In your case rename the second occurrence of "ArcGIS Server"  to "ArcGIS Image Server" or "ArcGIS Server2".  The name does not matter in almost all scenarios. Its the activation numbers that are really the key piece of information

@CViles can provide the exact details and correct me if necessary

**Comment by Biboba** [comment]
@nshampur Many thanks for your quick reply and fix 🥇

**Comment by CViles** [comment]
@Biboba actually please use "ArcGIS Server2" rather than "ArcGIS Image Server"!

The Software Authorization Wizard is designed to only authorize a single core product at a time, which effectively means that the last core product in the provisioning file is the only one used.  This is why only one of your current roles is being authorized.  The provisioning name "ArcGIS Image Server" is *also* a valid core product name, which would result in the exact same issue continuing to occur!

**Comment by Biboba** [comment]
@nshampur  and @CViles, I confirm that udating the variable name works.

With the following config file, ArcGIS Server role, Image Server role and Network analyst extension were authorized in one shot:
// Features and authorization numbers
ArcGIS Server=ECPAAAAAAAAA
ArcGIS Server1=ECPBBBBBBBBBB
Network Analyst Server=ECPCCCCCCCCC

Thanks

**Comment by nshampur** [comment]
Closed as resolved
