### ISSUE TITLE
Additional parameter - ArcGIS Server directories location

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#166]
Hello,

I think it would be nice to be able to specify each default arcgisserver directories location in addition to a generic "ServerDirectoriesRootLocation".

Something like:

```
"ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
"ServerDirectories" : [{
   "Name" : "arcgiscache",
   "PhysicalPath" : "D:\\arcgisserver\\directories\\arcgiscache",
   "DirectoryType" : "CACHE"
}]
```

that would end up configured:

![Directories](https://user-images.githubusercontent.com/11556423/57573857-23895b00-742f-11e9-8a3a-4095a73f7cd5.PNG)

Many thanks for the tool !

**Comment by cameronkroeker** [comment]
@Biboba,

We have added the following parameters to the latest release, v3.0.0:

**ServerDirectoriesRootLocation** - If you're installing on a single machine, provide a local path; otherwise, provide a Network File Share path.

**ServerDirectories** - A JSON object representing a collection of server directories to create.

**ServerLogsLocation** - File path to the root of the log directories.

**LocalRepositoryPath** - Directory where the local config-store is stored when site is in read-only mode.

https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

And a sample config can be found here:

https://github.com/Esri/arcgis-powershell-dsc/blob/7d365cb94b9ae351797af2cce582dd8b811f1a49/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine.json#L52
