### ISSUE TITLE
Consider supporting a .cer SSL Certificate without a password

### ISSUE THREAD

**Issue by pfoppe** [Esri/arcgis-powershell-dsc#169]
Our agency Certificate Authority currently provides .cer SSL certificates without a password.  Unfortunately it seems that the arcgis powershell module has multiple checks for an SSL certificate password and if the password is not set then the module generates a self-signed certificate.  We then have to fix the IIS SSL Certificate after the InstallLicenceConfigure.  

Thanks for the consideration.

**Comment by pfoppe** [comment]
For reference... If a .cer file is specified, the PSDSC configure will generate a new self-signed certificate with the specified alias and assign that to the IIS 443 bindings:

> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Setting up SSL Binding with self signed certificate
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Creating Binding on Port 443 for https
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Finished Creating Binding on Port 443 for https
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Installing Self-Signed Certificate for DnsName www.example.com
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Creating New-SelfSignedCertificate for DNS:- www.example.com
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Creating using New-SelfSignedCertificate
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Finished Creating using New-SelfSignedCertificate
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Removing existing certificate at IIS:\SslBindings\0.0.0.0!443
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Installing Certificate with thumbprint <REDACTED> and subject CN=www.example.com into IIS Binding for Port 443
> [IIS_MACHINE]:  [[ArcGIS_IIS_TLS]WebAdaptorCertificateInstallIIS_MACHINE] Finished Installing Certificate

We then go in and manually upload the .cer and re-assign the binding the the trusted certificate file.

**Comment by sodtom** [comment]
Perhaps also/even support configurations to refer certificates directly from cloud keyvaults?

**Comment by cameronkroeker** [comment]
Hello @pfoppe,

With [v4.0.1](https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v4.0.1), there is a new attribute, **ConfigData.WebAdaptor.OverrideHTTPSBinding**. Set this to false, so that the existing ssl certificate in the IIS 443 binding will not be replaced. When **SslCertificates.Target** is set to `WebAdaptor` this will allow you to specify a .cer file for **SslCertificates.Path**.

- A value for **SslCertificates.CNameFQDN** is still needed, as this is what is used to construct the web adaptor registration url.
- The specified .cer file can be a dummy file, the ArcGIS Module does not import it into IIS  (there will need to be an existing SSL certificate assigned to the 443 binding)
- **SslCertificates.Password** and **SslCertificates.PasswordFilePath** are not required in this scenario.

Thanks,
Cameron K.
