### ISSUE TITLE
portal, server & datastore fail on first install attempt

### ISSUE THREAD

**Issue by elwoodhouse** [Esri/arcgis-powershell-dsc#304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* ArcGIS Data Store

### Configuration Files

[1_portal_&_hosting.txt](https://github.com/Esri/arcgis-powershell-dsc/files/5853770/1_portal_._hosting.txt)

### Expected Behavior

Portal, Server and Datastore components install successfully.

### Actual Behavior

Portal, Server and Datastore components fail to install. But if another script is run again with the same component, it successfully installs the second time.

### Steps to Reproduce

Provision new Azure servers then run the DSC scripts.

### Important Factoids

Running in Azure.

### References
First install attempt:
[ArcGISInstall-1-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/5853743/ArcGISInstall-1-Verbose.txt)
[ArcGISInstall-1-19-2021-6-46-35-PM-Error.txt](https://github.com/Esri/arcgis-powershell-dsc/files/5853736/ArcGISInstall-1-19-2021-6-46-35-PM-Error.txt)

Second attempt success:
[ArcGISInstall-2-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/5853751/ArcGISInstall-2-Verbose.txt)

The same behavior is for ArcGIS server and datastore.

**Comment by cameronkroeker** [comment]
Hi @elwoodhouse,

Based on the initial logs I suspect the portal setup exited silently prior to finishing the installation. The module may not catch the error because the setup is being ran silently (/qn), therefore if the setups fails an error isn't thrown. When this happens I recommend checking the Windows Event Application logs to see if there is an msi related error. One possibility is an msi collision with a process running in the background.

Few other observations\comments:

Looks like module v2.1.1 is being used to install ArcGIS Enterprise 10.6.1. If possible, I recommend using our latest module v3.1.1 as it includes allot of improvements over v2.1.1. For example, it no longer uses 7Zip to extract the setup achieves, and also allows you to specify different username/password for portal and server. However, keep in mind though that a few changes will need to be made to your existing json file.

**Here are some resources to help with transitioning to v3.1.1:**

Variables used in V3:
https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files

Portal/Server Administrator Account examples:
https://github.com/Esri/arcgis-powershell-dsc/wiki/ArcGIS-Server-Primary-Administrator-Account-and-Portal-for-ArcGIS-Initial-Administrator-Account-variables

V3. Command Line Parameters:
https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters

V3. Sample Config for Multi-machine deployment:
https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Base%20Deployment/BaseDeployment-MultiMachine.json

> Note none of the modules currently support importing an ssl certificate into Data Store, so this can be removed from the json:

```
"SslCertificates" : [
                {
                    "Path" : "C:\\ArcGIS\\Certificates\\Wildcard-TST.pfx" ,
                    "Password" : "#{wildCardCertificateName}#" ,
                    "Alias" : "#{dataStore2}#" ,
                    "Target" : [ "DataStore" ]
                }
            ]
```

I also wouldn't recommend storing the portal content dir inside the install dir:

```
"ContentDirectoryLocation" : "C:\\Program Files\\Esri\\ArcGIS\\Portal\\Content\\arcgisportal\\content" ,
"ContentDir" : "C:\\Program Files\\Esri\\ArcGIS\\Portal\\Content"
```

I would recommend something like this:

```
"ContentDirectoryLocation" : "C:\\arcgisportal\\content" ,
"ContentDir" : "C:\\arcgisportal"
```

Hope this helps!

Thanks,
Cameron K.

**Comment by elwoodhouse** [comment]
Thanks for the quick response Cameron. I have asked the client to upgrade to v3.1.1, knowing how I can tell in the logs when that happens through 7zip will help.

I'll review the windows logs and report back if after upgrading we encounter that same issue.

Cheers,
Leon.

**Comment by cameronkroeker** [comment]
Starting in v3.2.0, We have added -EnableMSILogging switch to help capture silent installation logs of the setups.

https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters

```
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode InstallLicenseConfigure -EnableMSILogging
```

https://github.com/Esri/arcgis-powershell-dsc/releases/tag/v3.2.0
