### ISSUE TITLE
Enhancement - Add Support for Azure Storage Account File Share "private endpoint"

### ISSUE THREAD

**Issue by jturco** [Esri/arcgis-powershell-dsc#308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.1.1

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Enhancement

When trying to create the ArcGIS Server site with a CloudStorage account option, the "CreateSite" operation fails if the StorageAccount Fileshare was created using a private endpoint.  I have not tested this on portal but i suspect that option would fail as well as there seems to be an underlying issues with the user account accessing the fileshare.

**Comment by cameronkroeker** [comment]
After some review, there aren't any changes needed within the ArcGIS Module to support Azure Storage File Share private endpoints. For `ConfigStoreCloudStorageAccount.Username` attribute the ArcGIS Module accepts `StorageAccountA.blob.core.windows.net`. 

According to the Microsoft documentation, [Use private endpoints for Azure Storage](https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#dns-changes-for-private-endpoints), DNS handles the routing to the private link. 

_Clients on a VNet using the private endpoint should use the same connection string for the storage account as clients connecting to the public endpoint. We rely upon DNS resolution to automatically route the connections from the VNet to the storage account over a private link._

_Use the same connection string to connect to the storage account using private endpoints as you'd use otherwise. Please don't connect to the storage account using its privatelink subdomain URL._

_By default, We create a [private DNS zone](https://learn.microsoft.com/en-us/azure/dns/private-dns-overview) attached to the VNet with the necessary updates for the private endpoints. However, if you're using your own DNS server, you may need to make additional changes to your DNS configuration. The section on [DNS changes](https://learn.microsoft.com/en-us/azure/storage/common/storage-private-endpoints#dns-changes-for-private-endpoints) below describes the updates required for private endpoints._

The DNS resource records for StorageAccountA, when resolved by a client in the VNet hosting the private endpoint, will be:

![Untitled picture8](https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/025ac711-b962-40a3-bf2e-9d4fb2c12b8b)

Furthermore, in [Tutorial: Connect to a storage account using an Azure Private Endpoint](https://learn.microsoft.com/en-us/azure/private-link/tutorial-private-endpoint-storage-portal):

![Untitled picture9](https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/b13bdb07-16cd-46e5-b853-3a49a34aab98)

Thanks,
Cameron K.
