### ISSUE TITLE
Variable Documentation Improvement for FileShareLocalPath & ExternalFileSharePath + ServerRole

### ISSUE THREAD

**Issue by runneals** [Esri/arcgis-powershell-dsc#315]
Looking at the Variables page: https://github.com/Esri/arcgis-powershell-dsc/wiki/V3.-Variables-reference-page-for-JSON-configuration-files the FileShareLocalPath & ExternalFileSharePath under DataStoreItems > RasterStore need to be better defined. Do you need both?

Also is it possible to assign more than 1 ServerRole? Looking at our raster analytics, it was assigned both: GeneralPurposeServer,RasterAnalytics

**Comment by cameronkroeker** [comment]
Hi @runneals ,

If you'd like the DSC to create the RasterStore file share then specify both **ConfigData.DataStoreItems.FileShareName** and **ConfigData.DataStoreItems.FileShareLocalPath** otherwise if you have an existing file share then use **ConfigData.DataStoreItems.ExternalFileSharePath**.

You can only define one **Config.ServerRole** per json file. The **Config.ServerRole** does a couple of things. It helps the DSC determine which kind of Server is going to be installed/configured, for example: ArcGIS Server, ArcGIS Mission Server, ArcGIS Notebook Server, ArcGIS GeoEvent Server, etc. And it will also determine which Server Function gets set during federation.

If both GeneralPurposeServer, and RasterAnalytics are set as the Server Function for federation, then likely two json files were ran for the same Server. For example:

1. https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-GeneralPurpose.json
2. https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-RasterAnalytics-fileshare.json

or perhaps

1. https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Base%20Deployment/BaseDeployment-SingleMachine.json
2. https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/v3/Gis%20Servers/GISServer-RasterAnalytics-fileshare.json

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
The wiki has been updated.
