### ISSUE TITLE
DebugSwitch should have no impact on configuration !

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-powershell-dsc#338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 3.2.0

### Affected Resource(s)

* ArcGIS_Portal
* ArcGIS_Server

### Expected Behavior

Running a configuration with --DebugSwitch should not change the configuration run. As stated in the [Wiki](https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters), "DebugSwitch enables debug logging in the output stream for PowerShell DSC."

### Actual Behavior

Running a configuration with --DebugSwitch sets the ArcGIS for Server and Portal for ArcGIS log configuration to DEBUG mode instead of WARNING:

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/Modules/ArcGIS/Configurations-OnPrem/ArcGISServer.ps1#L388

https://github.com/Esri/arcgis-powershell-dsc/blob/78e488fc0aac6f8f4cdf574e1bdb50a7d39ed350/Modules/ArcGIS/Configurations-OnPrem/ArcGISPortal.ps1#L322

I was troubleshouting a performance issue and realized that the log settings of ArcGIS Server was set to DEBUG while I had never configured it !

### Steps to Reproduce

Run a configuration with --DebugSwitch

Thanks for listening !

/cc @ceddc

**Comment by cameronkroeker** [comment]
Hi @Biboba,

This is actually the intended use of the `-DebugSwitch` parameter. My apologies that the definition in the [wiki](https://github.com/Esri/arcgis-powershell-dsc/wiki/PowerShell-DSC-ArcGIS-Module-Command-Line-Parameters#parameters) was mis-leading. I have updated it to state the following:

**-DebugSwitch**

Changes the portal [logLevel](https://developers.arcgis.com/rest/enterprise-administration/portal/edit-log-settings.htm) and server [logLevel](https://developers.arcgis.com/rest/enterprise-administration/server/editlogsettings.htm) settings from WARNING to DEBUG. Additionally, it displays debug logging in the output stream for PowerShell DSC. 

> Note: This should only be used for debugging purposes only, when done debugging re-run DSC without the -DebugSwitch to change the server and portal logLevel back to WARNING.

If you wish to keep the server and portal log configuration at WARNING, then I recommend not using the `-DebugSwitch`, and just manually checking the DSC logs rather than relying on the DSC output stream. The DSC logs will contain the same level of logging with or without -DebugSwitch. 

Thanks,
Cameron K.

**Comment by Biboba** [comment]
Hi @cameronkroeker,

Thanks for the clarification and the update of the readme !
