### ISSUE TITLE
Enterprise 10.9.1 stuck at federation single server install w/ External name 

### ISSUE THREAD

**Issue by richardsr-saccounty** [Esri/arcgis-powershell-dsc#405]
We are having issues with installation/configurations hanging when obtaining a token from the portal during federation. The experience has been very similar to those reported in this past issue: https://github.com/Esri/arcgis-powershell-dsc/issues/160

It seems changes were made since 3.3.0 which is now making our configuation fail and we do not understand why the CNameFQDN is being used or causing this time out issue. 

### Module Version

* 3.3.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* Federation

### Expected Behavior
Expected the config to install using the External name and check out a token using the External name. 

### Actual Behavior
The installation fails and times out when obtaining a token from the portal to use for federation

7/8/2022 11:17:58 AM: [DTCGISU-AGE41]:                            [[ArcGIS_Federation]Federate] Get Portal Token from Deployment 'portaltest.xxxxx.com'
7/8/2022 12:24:40 PM: [DTCGISU-AGE41]: LCM:  [ End    Test     ]  [[ArcGIS_Federation]Federate]  in 4005.4010 seconds.
7/8/2022 12:24:40 PM: [DTCGISU-AGE41]: LCM:  [ End    Set      ]
7/8/2022 12:24:40 PM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 7/8/2022 12:24:40 PM: PowerShell DSC resource ArcGIS_Federation  failed to execute Test-TargetResource functionality with error 
message: Unable to retrieve Portal Token for 'siteadmin' from Deployment 'portaltest.xxxxx.com' 

### Steps to Reproduce
Use the External name in the CNameFQDN value

"SslCertificates": [
                {
                    "Path": "C:\\installfiles\\cert_age41.pfx",
                    "Password": "redacted",
                    "CNameFQDN": "portaltest.xxxxx.com",
                    "Target": [
                        "DataStore",
						"Portal",
						"Server",
						"WebAdaptor"
                    ]
                }
            ]

### Important Factoids
This used to work in past versions as we did not have this issue with the original 10.9.1 release in November with the module version 3.3.0

**Comment by cameronkroeker** [comment]
Hi @richardsr-saccounty,

This is likely due to the following:

https://github.com/Esri/arcgis-powershell-dsc/blob/6ee6c84c096dcb30b9acf80a022bddf704873594/Modules/ArcGIS/ArcGIS.psm1#L1610-L1614

During federation, if **ConfigData.Portal.InternalLoadBalancer** parameter is not specified in the configuration json then it will construct the portal url to generate the token using the value specified for the primary portal CNameFQDN.

Is there a reason why the external name is being set for the internal portal certificate that is being used for 7443? I recommend using the fully qualified internal portal hostname instead. For example:

```json
"SslCertificates": [
   {
      "Path": "C:\\installfiles\\cert_age41.pfx",
      "Password": "redacted",
      "CNameFQDN": "portaltest.xxxxx.com",
      "Target": [
         "DataStore",
         "Server",
         "WebAdaptor"
      ]
   },
   {
      "Path": "C:\\installfiles\\cert_age41.pfx",
      "Password": "redacted",
      "CNameFQDN": "internal-portal-hostname.domain.com",
      "Target": [
         "Portal"
      ]
   }
]
```

Thanks,
Cameron K.

**Comment by cameronkroeker** [comment]
> Thanks for the information and suggestion. We will experiement using the InternalLoadBalancer parameter and see if it works for us.
> 
> For use this provided some flexibility but infrequent situations allowing the IIS web adaptor to be configured with the external name. It was helpful when building parallel environments (system upgrades, DR, upgrade testing) without true network isolation before behind the F5.

Keep in mind you can specify the fully qualified internal hostname of the primary portal for **ConfigData.Portal.InternalLoadBalancer** attribute, but this will also get set as the privatePortalURL in portal's system properties, which is fine (in most cases) for single portal environments, but not ideal for highly available portal deployments (would become a single point of failure).

"_For use this provided some flexibility but infrequent situations allowing the IIS web adaptor to be configured with the external name. It was helpful when building parallel environments (system upgrades, DR, upgrade testing) without true network isolation before behind the F5._"

The json example I gave should satisfy this use case because the WebAdaptor CNameFQDN can still be set to the external name just like before, but the certificate being imported in portal will just be named internal-portal-hostname.domain.com rather than portaltest.xxxxx.com. It will then construct the following url to perform the federation:

https://internal-portal-hostname.domain.com:7443/arcgis

Thanks,
Cameron K.

**Comment by richardsr-saccounty** [comment]
Again thank you for this information. We have done a few more deployments with your recommendations and have not run into these issues.
