### ISSUE TITLE
WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the computer [FQDN for Portal Machine]

### ISSUE THREAD

**Issue by FeralCatColonist** [Esri/arcgis-powershell-dsc#453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.0.2

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal

### Configuration Files

```json
{
    "AllNodes": [
        {
            "NodeName": "ToP-ArcGIS-T03",
            "DataStoreTypes": [
                "Relational",
                "SpatioTemporal"
            ],
            "Role": [
                "DataStore"
            ],
            "SslCertificates": [
                {
                    "Path": "C:\\config\\certificate.pfx",
                    "Password": "[REDACTED]",
                    "CNameFQDN": "dev-datastore.prospertx.gov",
                    "Target": [
                        "DataStore"
                    ]
                }
            ]
        },
        {
            "NodeName": "ToP-ArcGIS-T02",
            "Role": [
                "Portal",
                "PortalWebAdaptor"
            ],
            "SslCertificates": [
                {
                    "Path": "C:\\config\\certificate.pfx",
                    "Password": "[REDACTED]",
                    "CNameFQDN": "dev-data.prospertx.gov",
                    "Target": [
                        "Portal",
                        "PortalWebAdaptor"
                    ]
                }
            ]
        },
        {
            "NodeName": "ToP-ArcGIS-T01",
            "Role": [
                "Server",
                "ServerWebAdaptor"
            ],
            "SslCertificates": [
                {
                    "Path": "C:\\config\\certificate.pfx",
                    "Password": "[REDACTED]",
                    "CNameFQDN": "dev-maps.prospertx.gov",
                    "Target": [
                        "Server",
                        "ServerWebAdaptor"
                    ]
                }
            ]
        }
    ],
    "ConfigData": {
        "Version": "10.8.1",
        "ServerContext": "server",
        "PortalContext": "portal",
        "ServerRole": "GeneralPurposeServer",
        "DownloadPatches":false,
        "Credentials": {
            "ServiceAccount": {
                "UserName": "[REDACTED]",
                "Password": "[REDACTED]",
                "IsDomainAccount": true,
                "IsMSAAccount": false
            },
            "ADServiceUser": {
                "UserName": "[REDACTED]",
                "Password": "[REDACTED]",
            }
        },
        "Server": {
            "LicenseFilePath": "C:\\arcgis_software\\ArcGISGISServerAdvanced_ArcGISServer_1286679.prvc",
            "Installer": {
                "Path": "C:\\arcgis_software\\ArcGIS_Server_Windows_1081_175203.exe",
                "InstallDir": "C:\\ArcGIS\\Server",
                "InstallDirPython": "C:\\Python27",
                "EnableArcMapRuntime": false,
                "EnableDotnetSupport": true,
                "EnableHTTPSOnly":true,
                "PatchesDir": "C:\\arcgis_patches"
            },
            "ServerDirectoriesRootLocation": "C:\\arcgisserver\\directories",
            "ConfigStoreLocation": "C:\\arcgisserver\\config-store",
            "PrimarySiteAdmin": {
                "UserName": "[REDACTED]",
                "Password": "[REDACTED]",
            }
        },
        "Portal": {
            "LicenseFilePath": "C:\\arcgis_software\\ArcGIS_Enterprise_Portal_1081_409372_20230218.json",
            "PortalLicenseUserTypeId": "creatorUT",
            "Installer": {
                "Path": "C:\\arcgis_software\\Portal_for_ArcGIS_Windows_1081_175214.exe",
                "WebStylesPath": "C:\\arcgis_software\\Portal_for_ArcGIS_Web_Styles_Windows_1081_175215.exe",
                "InstallDir": "C:\\ArcGIS\\Portal",
                "ContentDir": "C:\\arcgisportal",
                "PatchesDir": "C:\\arcgis_patches"
            },
            "ContentDirectoryLocation":"C:\\arcgisportal\\content",
            "DisableAnonymousAccess ":true,
            "EnableAutomaticAccountCreation":true,
            "DefaultRoleForUser": "iAAAAAAAAAAAAAAA (Viewer)",
            "DefaultUserLicenseTypeIdForUser":"viewerUT",
            "PortalAdministrator": {
                "UserName": "[REDACTED]",
                "Email": "[REDACTED]",
                "Password": "[REDACTED]",
                "SecurityQuestionIndex": "[REDACTED]",
                "SecurityAnswer": "[REDACTED]",
            }
        },
        "DataStore": {
            "ContentDirectoryLocation": "C:\\arcgisdatastore",
            "EnableFailoverOnPrimaryStop": false,
            "Installer": {
                "Path": "C:\\arcgis_software\\ArcGIS_DataStore_Windows_1081_175216.exe",
                "InstallDir": "C:\\ArcGIS\\DataStore",
                "PatchesDir": "C:\\arcgis_patches"
            }
        },
        "WebAdaptor": {
            "AdminAccessEnabled": true,
            "Installer": {
                "Path": "C:\\arcgis_software\\ArcGIS_Web_Adaptor_for_Microsoft_IIS_1081_175217.exe"
            }
        }
    }
}
```

### Expected Behavior

ArcGIS Federates correctly.

### Actual Behavior

```powershell
Starting DSC Job:- ArcGISFederation
VERBOSE: Time taken for configuration job to complete is 0.009 seconds
2/22/2023 9:37:05 PM: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
2/22/2023 9:37:10 PM: An LCM method call arrived from computer TOP-ARCGIS-T01 with user sid [probably sensitive?].
2/22/2023 9:37:10 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Set      ]
2/22/2023 9:37:10 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Resource ]  [[ArcGIS_Federation]Federate]
2/22/2023 9:37:10 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Test     ]  [[ArcGIS_Federation]Federate]
2/22/2023 9:37:10 PM: [TOP-ARCGIS-T01]:                            [[ArcGIS_Federation]Federate] Get Portal Token from Deployment 'TOP-ARCGIS-T01.'
Trace-DSCJob : 2/22/2023 9:37:10 PM: WinRM cannot process the request. The following error occurred while using Kerberos authentication: Cannot find the computer
dev-data.prospertx.gov. Verify that the computer exists on the network and that the name provided is spelled correctly.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

2/22/2023 10:56:21 PM: [TOP-ARCGIS-T01]: LCM:  [ End    Test     ]  [[ArcGIS_Federation]Federate]  in 4753.8940 seconds.
2/22/2023 10:56:22 PM: [TOP-ARCGIS-T01]: LCM:  [ End    Set      ]
2/22/2023 10:56:22 PM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 2/22/2023 10:56:22 PM: PowerShell DSC resource ArcGIS_Federation  failed to execute Test-TargetResource functionality with error message: Unable to
retrieve Portal Token for 'REDACTED' from Deployment 'TOP-ARCGIS-T01.'
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 2/22/2023 10:56:22 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- ArcGISFederation. Time Taken - 01:19:16.7917417
```

I'm definitely out of my depth with Powershell and IIS stuff generally, so please excuse the simplistic questions here:
- Why it is trying to find the computer through the FQDN instead of the computer name?
- I thought it would retrieve the Portal Token from the Portal Machine: TOP-ARCGIS-T02, instead of the Server Machine TOP-ARCGIS-T01?
- Is the DSC supposed to fully apply the certificate and IIS settings, or are there some additional manual things that need to be done here?
- I re-ran the invoke again this morning and have received the same errors, waiting for the 50-minute gap to get the second error message pertaining to the retrieval of the token.

### Steps to Reproduce

run the configuration
```powershell
Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment-ThreeMachine.json -Mode InstallLicenseConfigure -Credential -MappedDriveOverrideFlag $True
```

### Important Factoids

- This is a wildcard certificate in .pfx format (has been tested and verified elsewhere in our infrastructure)
- Windows Server 2022 Standard, 21H2

**Comment by FeralCatColonist** [comment]
Some of this was resolved when I learned a little bit about wildcards, when you have a wildcard certificate, you must import it into your IIS. The GUI way is like IIS -> localhost(your computer name) -> Server Certificates -> Import. After this is done, the friendly name of the machine is assigned by resolving the DNS, which your "web people" should be familiar with.

I am still unable to retrieve the token from the portal admin account:

```powershell
Starting DSC Job:- ArcGISFederation
VERBOSE: Time taken for configuration job to complete is 0.01 seconds
2/24/2023 2:07:26 PM: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
2/24/2023 2:07:31 PM: An LCM method call arrived from computer TOP-ARCGIS-T01 with user sid [probably sensitive?].
2/24/2023 2:07:31 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Set      ]
2/24/2023 2:07:31 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Resource ]  [[ArcGIS_Federation]Federate]
2/24/2023 2:07:31 PM: [TOP-ARCGIS-T01]: LCM:  [ Start  Test     ]  [[ArcGIS_Federation]Federate]
2/24/2023 2:07:31 PM: [TOP-ARCGIS-T01]:                            [[ArcGIS_Federation]Federate] Get Portal Token from Deployment 'dev-data.prospertx.gov'
2/24/2023 3:10:08 PM: [TOP-ARCGIS-T01]: LCM:  [ End    Test     ]  [[ArcGIS_Federation]Federate]  in 3758.0730 seconds.
2/24/2023 3:10:08 PM: [TOP-ARCGIS-T01]: LCM:  [ End    Set      ]
2/24/2023 3:10:08 PM: Operation 'Invoke CimMethod' complete.
Trace-DSCJob : 2/24/2023 3:10:08 PM: PowerShell DSC resource ArcGIS_Federation  failed to execute Test-TargetResource functionality with error message:
Unable to retrieve Portal Token for '[REDACTED]' from Deployment 'dev-data.prospertx.gov'
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 2/24/2023 3:10:08 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- ArcGISFederation. Time Taken - 01:02:41.4107838
ArcGISFederation - Failed
```

I do have an adjacent question, should IIS also be installed on the Data Store machine?
- From the parameters, on the sample [ssl-per-node], we're attaching an SSL to the datastore machine as well, meaning the intent is to connect to it directly.
- If that's the case, it sounds like IIS should also be installed on that correct?

![image](https://user-images.githubusercontent.com/12204584/221274973-74ba71b5-f9ab-4f91-a166-6d6164e28c09.png)

**Comment by cameronkroeker** [comment]
Hi @FeralCatColonist,

- I thought it would retrieve the Portal Token from the Portal Machine: TOP-ARCGIS-T02, instead of the Server Machine TOP-ARCGIS-T01?

_The ArcGIS Module will perform the federation from the node where ArcGIS Server is installed. This is because when federating additional server roles, the Module does not have the ability to connect to the portal node._

- Is the DSC supposed to fully apply the certificate and IIS settings, or are there some additional manual things that need to be done here?

_As long as the ConfigData.WebAdaptor.OverrideHTTPSBinding is set to true (default), the ArcGIS Module will enabled IIS on the Web Adaptor Node, enable the https binding (443) and import the ssl certificate into IIS, no additional manual configuration is required._

- I do have an adjacent question, should IIS also be installed on the Data Store machine?

_No IIS is not needed or used for ArcGIS Data Store. When SslCertificates.Target is set to DataStore, the ssl certificate gets imported directly into ArcGIS Data Store's internal web server (tomcat), and is used for port 2443. Additional information can be found here_ :

https://enterprise.arcgis.com/en/portal/latest/administer/windows/update-ads-ssl-certificate.htm

I suspect the federation issue is coming from this part of the code:

https://github.com/Esri/arcgis-powershell-dsc/blob/ebd5e9a6e896b3326e2d06be14255bc235036948/Modules/ArcGIS/ArcGIS.psm1#L1734

Since `ConfigData.Portal.InternalLoadBalancer` attribute is not specified in your json the module will fall back to using the value specified for `SslCertificates.CNameFQDN` to construct the portal url via port 7443. So it is likely trying to generate a token using `https://dev-data.prospertx.gov:7443/arcgis` instead of `https://ToP-ArcGIS-T02.yourdomain.gov:7443/arcgis`.

To work around this you could set `ConfigData.Portal.InternalLoadBalancer` to ToP-ArcGIS-T02.yourdomain.gov in your json file. Keep in mind this will then also be used as the [privatePortalURL in system properties](https://developers.arcgis.com/rest/enterprise-administration/portal/system-properties.htm). Which is fine for single machine deployments but for highly available deployments you would want this to be a load balanced url.

Another option is to specify the internal FQDN of the portal node ToP-ArcGIS-T02.yourdomain.gov for `SslCertificates.CNameFQDN`.

Thanks,
Cameron K.

**Comment by FeralCatColonist** [comment]
Hey @cameronkroeker thanks for taking the time to respond. I stumbled onto issue thread (https://github.com/Esri/arcgis-powershell-dsc/issues/405) this morning and implemented the change to `ConfigData.Portal.InternalLoadBalancer`; however, based on your response above I think that I'll revert the config json to utilizing `SslCertificates.CNameFQDN` with the internal FQDN (which I learned about today, it was set to be the same as the external).

- Would I re-run the invoke in `-Mode InstallLicenseConfigure` to make the change?
    - I keep uninstalling and reinstalling the whole deployment to help me wrap my head around these changes and to prevent anything unexpected from happening that isn't fully documented within the DSC config json
    - I'm a bit unsure of when it is appropriate to re-run the invoke vs. razing it to the ground :fire:
- It seems to me that the preferred method is to utilize the internal FQDN for `SslCertificates.CNameFQDN`?
    - is this a result of utilizing a wildcard certificate?
    - should the documentation be enhanced to include a note on this topic?
    - does this logic apply to the other components or just the data store?

After running the invoke in `-Mode Uninstall`, and then attempting to reinstall, the following error is raised:

```powershell
Trace-DSCJob : 2/27/2023 4:20:49 PM: PowerShell DSC resource ArcGIS_Portal  failed to execute Set-TargetResource functionality with error message: [Error] - Response:-
{"status":"error","messages":["The portal site has not been upgraded. Please upgrade the site and try
again."],"isUpgrade":true,"resources":["license"],"isPortalLicensed":true,"isLicenseFileRequired":false,"isUserTypeLicensing":true,"version":"10.9.1"}
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 2/27/2023 4:20:49 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

My workaround has been to delete the installed folders using robocopy: arcgisserver, arcgisportal, arcgisdatastore.
- Is that the intended workflow?
- Or is the uninstall supposed to also remove those components completely?

**Comment by cameronkroeker** [comment]
Hi @FeralCatColonist,

Based on the error it looks as if portal is in upgrade mode rather than create site mode. At some point after one of the reinstall attempts the portal create site failed and portal didn't rollback properly to create site mode. This can happen when portal removes the config-store-connection.json from install_dir/framework/etc directory, but doesn't remove it's .../arcgisportal/db folder. You can try to salvage it by:

1. Stop portal Windows service in services.msc.
2. Ensure the install_dir/framework/etc/config-store-connection.json doesn't exist. If it does rename or delete it.
3. Rename or delete:
   - .../arcgisportal/db
   - .../arcgisportal/index
   - .../arcgisportal/dsdata
4. Start portal Window service in services.msc.
5. After a few minutes, browse to https://ToP-ArcGIS-T02.domain.gov:7443/arcgis/home or https://ToP-ArcGIS-T02.domain.gov:7443/arcgis/portaladmin to ensure its back in create site mode rather than upgrade mode. You should see two options: create site or join site. Do not proceed with either of these, this is just to confirm that portal is no longer in upgrade mode.
6. Make your adjustments to your json config file, and re-run DSC.

If this doesn't work then, I recommend uninstalling (`-Mode Uninstall`), and then once this completes remove all traces of portal (delete install directory and arcgisportal directory) to start fresh before reinstalling. The ArcGIS Module does not delete or remove the installation directories or content/data directories, it will only perform a typical [silent uninstall ](https://enterprise.arcgis.com/en/portal/latest/install/windows/uninstalling-portal-for-arcgis.htm#GUID-91453D45-3E5D-4223-8D2F-49962003F0DA) of each component (this is to preserve any content/data that users may have incase they wish to reinstall).

The `SslCertificates.CNameFQDN` for portal/server/datastore is used as the `webServerCertificateAlias` (name of the certificate) for [importing ssl certificate](https://developers.arcgis.com/rest/enterprise-administration/portal/update-web-server-certificate.htm) into internal web server (tomcat) which is used for the internal FQDN and port 7443/6443/2443. For Web Adaptor it is used as the hostname for the web adaptor registration url.

https://github.com/Esri/arcgis-powershell-dsc/blob/ebd5e9a6e896b3326e2d06be14255bc235036948/Modules/ArcGIS/Configurations-OnPrem/ArcGISWebAdaptor.ps1#L117

Another use case for `ConfigData.Portal.InternalLoadBalancer` is when using Integrated Windows Authentication (IWA). If IWA is used then the privatePortalUrl will need to be set to an internally accessible url that by passes IWA. There are additional details here: https://github.com/Esri/arcgis-powershell-dsc/issues/434#issuecomment-1349107576

Yes, I agree the documentation does need to include all of this information in a more detailed and clear/concise manner. Updating/overhauling the documentation is on our road map.

Thanks,
Cameron K.

**Comment by FeralCatColonist** [comment]
I've successfully completed the installation in our development environment. Thanks again for all your help. I set the `ConfigData.Portal.InternalLoadBalancer` to the internal DNS name and kept the `SslCertificates.CNameFQDN` set to the external DNS name.

I think that the issue here concerns the wildcard certificate since it is not baking in an FQDN and instead looks like `*.domain.com`. In our current production environment, our certificate is for a single site only and has the FQDN embedded like `portal.domain.com`.

**Comment by FeralCatColonist** [comment]
It is possible to deploy the DSC utilizing a wildcard certificate right? like `*.domain.com`

I got to the federation bit and it broke apart with this error:
```powershell
Trace-DSCJob : 3/3/2023 1:56:45 PM: PowerShell DSC resource ArcGIS_Federation  failed to execute Set-TargetResource functionality with error message: [ERROR]:- Federation Failed after multiple attempts. Error:- @{code=500;
message=Failed to federate ArcGIS Server site 'https://ToP-ArcGIS-T01.TownofProsper.local:6443/arcgis' with Portal for ArcGIS. Unable to validate TLS certificate on ArcGIS Server administration URL. Ensure the root certificate is
trusted or the certificate common name matches the URL hostname.; details=}
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 3/3/2023 1:56:45 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\4.0.2\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob
```

I'm looking at a few resources now like [this](https://gis.wsu.edu/portal/portalhelp/en/server/latest/deploy/windows/federate-an-arcgis-server-site-with-your-portal.htm#:~:text=if%20you%20are%20federating%20an%20arcgis%20server%20that%20uses%20a%20wildcard%20security%20certificate), [this](https://community.esri.com/t5/arcgis-enterprise-portal-questions/federation-unable-to-validate-tls-certificate-10-9/td-p/1233118), [and this](https://enterprise.arcgis.com/en/portal/latest/administer/windows/configure-servers.htm). I'm guessing that I'll need to make manual modifications each time? Is the DSC equipped to handle a wildcard certificate? If not, what option should I use?
- self-signed then configure certificate afterwards?
- run it, let it error, and then configure within the portal admin?

**Comment by cameronkroeker** [comment]
Hi @FeralCatColonist,

Yes, using a wild card certificate is supported. However, based on the error, portal does not trust the Certificate Authority (CA) that has signed the wild card certificate. Portal by default trusts most well known CA's but not all, or if its a Domain Signed certificate it won't trust it at all. In this case, you will need to also import the root certificate (and possibly all intermediate certificates) into portal so that it can trust the CA that signed the wild card certificate. You can do this via the ArcGIS Module by passing in an array of root/intermediate certificates into your json config file using the `SslCertificates.SslRootOrIntermediate` attribute:

https://github.com/Esri/arcgis-powershell-dsc/blob/ebd5e9a6e896b3326e2d06be14255bc235036948/SampleConfigs/v4/v4.0.2/Base%20Deployment/BaseDeployment-ThreeMachine-ssl-per-Node-Example2.json#L64-L83

**Another example:**
```json
"SslCertificates":[
              {
               "Path":"C:\\config\\certificate.pfx",
               "Password":"[REDACTED]",
               "CNameFQDN":"dev-data.prospertx.gov",
               "Target":["Portal"],
		       "SslRootOrIntermediate": [
		        {
			     "Alias": "wild-card-root-ca",
			     "Path": "C:\\config\\certificate-wild-card-root-ca.cer"
		        },
			    {
			     "Alias": "wild-card-intermediate",
			     "Path": "C:\\config\\certificate-wild-card-intermediate-issuing-ca.cer"
		        }
	           ]
              },
```

I have a question. If portal's internal fqdn is ToP-ArcGIS-T02.INTERNALDOMAIN.local, what is the reason for importing a certificate that is issued to *.prospertx.gov? I would think this would cause an ssl certificate mismatched name error when browsing to:

https://ToP-ArcGIS-T02.INTERNALDOMAIN.local:7443/arcgis/portaladmin

Unless of course *INTERNALDOMAIN.local is added the Subject Alternative Name (SAN) of the wild card certificate.

Thanks,
Cameron K.

**Comment by FeralCatColonist** [comment]
Hey @cameronkroeker,

We're using a wildcard issued by GoDaddy, which I am assuming would be fairly well-known. As you saw in the config the base was a .pfx. Now my understanding is that the .pfx. is a combination of a certificate with a private key attached. What I did was open the `mmc` from the command line and traverse to where the certificates for the machine are located. Once there, I opened the wildcard and see that it had its lineage presented. So I used the export function to export the intermediate and roots to `.cer` files.

I'm not a web person and the best analogy I have is, it's a bit of guild-style knowledge here.
- Is this something that is able to be abstracted away by the DSC, i.e. traversing the wildcard certificate upwards?
- I'm wondering how Windows Server "knows" the lineage of the wildcard certificate?
- Or how would one *know* to grab out the intermediate and root?

![image](https://user-images.githubusercontent.com/12204584/222829770-792cbe0b-62ca-4a97-aced-2307d1f870cd.png)

> I have a question. If portal's internal fqdn is ToP-ArcGIS-T02.INTERNALDOMAIN.local, what is the reason for importing a certificate that is issued to *.prospertx.gov?

I have the web adaptors co-located for each server and portal box-- --if there's a smarter/better way to do this I'm open to that. And again, this stretches the non-existent amount of web knowledge I have; I'm assuming that an internal domain that differs from the external is a more secure resource? I'm trying really hard not to overthink it, I wish I could say, "you know what box you're on, this is the external address that people expect to see, now do the thing."

A lot of documentation takes the approach of, everyone's deployment is unique, so do what you want. And I'd really appreciate an alternative approach like:

**This is what we recommend and why, but feel free to deviate**

This kind of blueprinting would be useful to the vast majority of organizations. Those that don't fit the box likely have plenty of in-house talent and resources to explore alternative configurations. Again, back to the guild-style knowledge tracks, most of what I've picked up is from the few books on the subject or hearing something from a GIS Manager with the flavor of "We do it this way because it works and we don't want to break it"

So the federation completed successfully and I'm getting an invalid redirect:
![image](https://user-images.githubusercontent.com/12204584/222836011-f6fd7b6f-041f-49a6-a5a0-465077b0f02d.png)
I'm guessing that I need to follow this flow? Or is this a result of me mi-configuring the DSC?
https://support.esri.com/en/technical-article/000015445#:~:text=The%20error%20may%20occur%20due,Qualified%20Domain%20Name%20(FQDN).

**Comment by FeralCatColonist** [comment]
Thanks for all the help with this! The issue stemmed from needing to have the `ExternalLoadBalancer` parameter set for Server and Portal. This allows the appropriate web context to be set and populates the correct security settings as well.
`Portal.ExernalLoadBalancer: "dev-data.prospertx.gov"`
`Server.ExernalLoadBalancer: "dev-maps.prospertx.gov"`
