### ISSUE TITLE
Download and install all available patches 10.9.1

### ISSUE THREAD

**Issue by widsuoids** [Esri/arcgis-powershell-dsc#477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

4.1.0

### Affected Resource(s)
https://github.com/Esri/arcgis-powershell-dsc/wiki/Download-and-Install-patches-for-ArcGIS-Enterprise

For ArcGIS Server 10.9.1 it is recommended to use ConfigData.Server.Installer.PatchInstallOrder so that the [Setup Program Patch](https://support.esri.com/en-us/patches-updates/2021/arcgis-server-10-9-1-setup-program-patch-7956) can be installed first. For example:
"PatchInstallOrder": [
   "ArcGIS-1091-S-SP-Patch.msp",
   "ArcGIS-1091-S-MR-PatchB.msp",
   "ArcGIS-1091-S-Log4j-PatchB.msp",
   "ArcGIS-1091-S-SEC2022U1-PatchB.msp",
   "ArcGIS-1091-S-SEC2022U2-Patch.msp",
   "ArcGIS-1091-S-MPS-Patch.msp",
   "ArcGIS-1091-S-UNDM1-Patch.msp",
   "ArcGIS-1091-S-UNDM2-Patch.msp",
   "ArcGIS-1091-S-K1-Patch.msp",
   "ArcGIS-1091-S-VRPG-Patch.msp",
   "ArcGIS-1091-S-SQ-Patch.msp",
   "ArcGIS-1091-S-UNDM3-Patch.msp",
   "ArcGIS-1091-S-GSQ-Patch.msp",
   "ArcGIS-1091-S-CPS-Patch.msp"
]

## Questions

How to configure "Download and install all available patches" for 10.9.1? 
Or will patches not listed in the PatchInstallOrder be downloaded and installed as well?

How to best get the latest Patch File Names?

**Comment by cameronkroeker** [comment]
Hi @widsuoids,

Applying patches for 10.9.1 is a bit tricky in that (so far) it is the only version where it requires a specific install order. When `PatchInstallOrder` is not used the module will download and install patches in order of release date. If you don't specify the `PatchInstallOrder` for 10.9.1 on the first run it will download and install all patches except for the Machine Rename patch (ArcGIS-1091-S-MR-PatchB.msp). This is because the ArcGIS-1091-S-MR-PatchB.msp patch was released prior to the Setup Program patch (ArcGIS-1091-S-SP-Patch.msp), however the Setup Program patch is required for patches to be installed. So in the scenario where you omit `PatchInstallOrder`, you will need to run `-Mode Install` a second time so that it will install the Machine Rename patch.

However, if you only want to run `-Mode Install` a single time to get all patches installed in a single run, then all the patches will need to be listed using `PatchInstallOrder`. The patch msp file names can be retrieved from https://support.esri.com/en-us/patches-updates, or https://downloads.esri.com/patch_notification/patchesPretty.json.

Thanks,
Cameron K.
