### ISSUE TITLE
Upgrade Base Deployment from 11.2 to 11.3

### ISSUE THREAD

**Issue by minagim** [Esri/arcgis-powershell-dsc#544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Module Version

* 4.3.0

### Affected Resource(s)

* ArcGIS_Server
* ArcGIS_Portal
* ArcGIS_DataStore
* ArcGIS_WebAdaptor

### Configuration Files

```
# Copy-paste your DSC JSON configurations here - for large configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Expected Behavior

Looks like upgrading order matters.  Can I use the Base Deployment for multi machine sample script to upgrade from 11.2 to 11.3?

Invoke-ArcGISConfiguration -ConfigurationParametersFile C:\config\BaseDeployment.json -Mode Upgrade -EnableMSILogging

**Comment by cameronkroeker** [comment]
Hi @minagim you will want to use your original 11.2 json configuration file for the upgrade to 11.3. A few modifications are required:

- Change **ConfigData.Version** to 11.3
- Add **ConfigData.OldVersion** and set to 11.2
- Update license files to 11.3
- Update installation files to 11.3
- Delete original module on orchestrating machine and all target nodes, and replace with latest module v4.30
- If **ConfigData.DownloadSetups** is set to true then add **ConfigData.Server.Installer.VolumePaths** and **ConfigData.Portal.Installer.VolumePaths** attributes so that will download the .exe.001 files.

Thanks,
Cameron K.

**Comment by minagim** [comment]
Thanks, Cameron.  
I am getting the following error when running the update.
Invoke-ArcGISConfiguration -ConfigurationParametersFile d:\Install\Scripts\ParksAzure_11_3_BaseDeployment-MultiMachine.json -Mode Upgrade -EnableMSILogging

Trace-DSCJob : 6/23/2024 8:10:36 PM: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource
functionality with error message: Failed to Install WebAdaptorIIS-Portal-portal
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Trace-DSCJob : 6/23/2024 8:10:36 PM: The SendConfigurationApply function did not succeed.
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:261 char:5
+     Trace-DSCJob -Job $Job -JobName $ConfigurationName -DebugMode $De ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Trace-DSCJob

Logs Directory: C:\Windows\system32\Logs
Finished DSC Job:- WebAdaptorUpgrade. Time Taken - 00:00:50.2774322
WebAdaptorUpgrade - Failed
Portal WebAdaptors Upgrade Failed
At C:\Program Files\WindowsPowerShell\Modules\ArcGIS\ArcGIS.psm1:2846 char:13
+             throw "Portal WebAdaptors Upgrade Failed"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Portal WebAdaptors Upgrade Failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Portal WebAdaptors Upgrade Failed

The following is in the error log.
6/21/2024: PowerShell DSC resource ArcGIS_Install  failed to execute Set-TargetResource functionality with error message: Failed to Install WebAdaptorIIS-Portal-portal 
6/21/2024: The SendConfigurationApply function did not succeed.

[ParksAzure_11_3_BaseDeployment-MultiMachine Share.json](https://github.com/user-attachments/files/15960904/ParksAzure_11_3_BaseDeployment-MultiMachine.Share.json)

Can you give me some guidance on this error?

Thanks,

Mina

**Comment by cameronkroeker** [comment]
Hi @minagim,

Can you check the MSI log for web adaptor? When passing in `-EnableMSILogging` it should capture a log of the silent installation that may provide more clues on the failure. By default it gets placed in C:\Windows\Temp.

I assume all the 11.3 Prerequisites are already pre-installed because I did not see them specified in your json config. For example, Web Deploy 3.6 or 4.0, and dot net hosting bundle 8?

https://enterprise.arcgis.com/en/system-requirements/latest/windows/arcgis-web-adaptor-system-requirements.htm#ESRI_SECTION1_B79830AA8CCE4FE4AD1E0981E8BAA2D1

<img width="784" alt="Screenshot 2024-06-24 at 2 07 48 PM" src="https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/6da03c72-8686-4539-bcfa-e670334f23ef">

If not, you can have the module install them:

https://github.com/Esri/arcgis-powershell-dsc/wiki/v4.3.0-Variables-reference-page-for-JSON-configuration-files

<img width="882" alt="Screenshot 2024-06-24 at 2 04 51 PM" src="https://github.com/Esri/arcgis-powershell-dsc/assets/48299621/ad7a5127-83ef-47bd-87c2-dbe186ca8abd">

Here is a sample of the json:
https://github.com/Esri/arcgis-powershell-dsc/blob/4e1ea910cf3c237c378dfcfc1130a296de3c4bcb/SampleConfigs/v4/v4.3.0/Base%20Deployment/BaseDeployment-SingleMachine.json#L194-L197

When those attributes are omitted from the json config it's assumed they are already installed.

Thanks,
Cameron K.

**Comment by minagim** [comment]
The ASP.NET Core Runtime was outdated and updating it resolved the issue and I was able to finish the upgrade.
Thanks for the advice, Cameron.  I will close the case.
