### ISSUE TITLE
Installation of root certificate

### ISSUE THREAD

**Issue by jbiendara** [Esri/arcgis-powershell-dsc#92]
Hello,
I still have problems with the installation of the root certificate (see also issues thread #90, question #7).
My test was to install a single machine image server including the ssl root certificate (as shown in BaseDeployment-ThreeMachine-10.6-ssl-per-Node.json). The installation finished without errors (see attached configuration file and log file). I would have expected to find the root certificate installed on that server, but it is not.

[ArcGISConfigure-05.09.2018-09-50-40-Verbose.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2351852/ArcGISConfigure-05.09.2018-09-50-40-Verbose.txt)
[vsdev2373_GISServer-GeneralPurpose_ImageServer.txt](https://github.com/Esri/arcgis-powershell-dsc/files/2351853/vsdev2373_GISServer-GeneralPurpose_ImageServer.txt)

1. Actually, where should the root certificate be installed in general, especially in a multi machine environment?

2. The ssl root certificate part is configured in the "ConfigData" - "Credentials" section of the configuration file. Where will this certificate be installed, eventually?

3. Do I also need to configure an intermediate certificate as well (as provided in the sample) or can I just omit the intermediate certificate part?

4. I want to install the root certificate on every server machine (Portal, hosted Server, Data Store, GeoEvent Server, Image Server) of my multi machine environment. What do I need to do?

Thank you very much, best regards,
Jürgen

**Comment by shailesh91** [comment]
Hey Jürgen,
Your configuration is wrong, the SSL root and intermediate variable is not part of the credentials object 
https://github.com/Esri/arcgis-powershell-dsc/blob/master/SampleConfigs/Base%20Deployment/BaseDeployment-ThreeMachine-10.6-ssl-per-Node.json

1. You need to specify all the root or intermediate certs in the config data. They will be installed on all machines.
2. It is just for reference, it is optional.
3. Just add it to your config data block so that it can be installed on every server machine.

Shailesh

**Comment by jbiendara** [comment]
Hello Shailesh,
Yes, you are right, I included the ssl root certificate part at the wrong position in the configuration file. Maybe I was mislead by the indentation of this part in the sample shown when following the given link.
Thank you very much, best regards,
Jürgen
